### ISSUE TITLE
Refacture Dialogs

### ISSUE THREAD

**Issue by k-d-ivanov** [stlevkov/budgeta#101]
Dialog can be used as separate component, for dialogs with common views
It can accept props with the data, fields, values from the parent component. 
Or may be return dialog data object to the parent for further processing 

Button invoking dialog could be part of the 'parent' component, because if there is a problem with dialog component you will end up
missing the button in 'parent' also

**Comment by stlevkov** [comment]
If there is a chance that the logic in the dialog component may fail on startup and result in errors or incomplete requests, it may be better to not render the button within the dialog component. This would prevent users from attempting to open the dialog and encountering errors.
