### ISSUE TITLE
Fix Unexpected, Expenses to not return default values upon error.

### ISSUE THREAD

**Issue by stlevkov** [stlevkov/budgeta#109]
This makes the user confused, because there are no yet any messages showing the error and the value is stil presented to the user, but not the DB value.

**Comment by k-d-ivanov** [comment]
After switching to RestClient the default values are no longer returned. 
Handling of  an empty values could be fixed in new issue in future.

**Comment by stlevkov** [comment]
Currently, a toast message is fired when request fails. It is enough to alarm the user that the value is not saved even if the dashboard is dynamically updated.
