### ISSUE TITLE
VS Code Extension Not Showing "HELLO WORLD" Command in Debug Mode

### ISSUE THREAD

**Issue by honeydreamchaser** [stlevkov/budgeta#268]
I'm attempting to develop a VS Code extension, following the [documentation provided here](https://code.visualstudio.com/api/get-started/your-first-extension). After creating the extension, I ran it using the Debug (F5) mode.

Subsequently, in the opened window, I pressed Cmd + Shift + P and entered Hello World, expecting to see the related command. However, the command did not appear.

How can I effectively debug this issue with my VS Code extension?

**Comment by hero09016** [comment]
Probably your VS Code version is lower than the version required in your extension. Try updating your VS Code to latest version and run the extension again.
